"""empty message

Revision ID: b16da1d04396
Revises: c4a28a55ab74
Create Date: 2022-05-24 13:51:10.526718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16da1d04396'
down_revision = 'c4a28a55ab74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cats',
    sa.Column('id_cat', sa.Integer(), nullable=False),
    sa.Column('nome_cat', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id_cat')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cats')
    # ### end Alembic commands ###
