"""empty message

Revision ID: c4a28a55ab74
Revises: 
Create Date: 2022-05-24 11:37:04.660789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4a28a55ab74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livros',
    sa.Column('id_livro', sa.Integer(), nullable=False),
    sa.Column('nome_livro', sa.String(length=128), nullable=True),
    sa.Column('cat', sa.String(length=64), nullable=True),
    sa.Column('autor', sa.String(length=64), nullable=True),
    sa.Column('classi', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_livro')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livros')
    # ### end Alembic commands ###
